version: '3'
services:

  # sbt用のキャッシュファイルを保存しておくコンテナ
  #buildcache:
  #  image: busybox
  #  volumes:
  #    - /buildcache/.ivy2/cache:/root/.ivy2/cache
  #    - /buildcache/.sbt/boot:/root/.sbt/boot

  # finatraが動くコンテナ
  finatra-server:
    working_dir: /app
    build: dockerfiles/finatra-server
    #command: activator run
    ports:
      - 9000:9000
    volumes:
      - .:/app
      - buildcache:/root/.ivy2/cache
      - buildcache:/root/.sbt/boot
    #command: sbt 'run -http.port=:9000 -http.name=:0.0.0.0'
    command: sbt '~re-start -http.port=:9000 -http.name=:0.0.0.0'
    #volumes_from:
    #  - buildcache
    stdin_open: true
volumes:
  buildcache:
